adds 2-typings
sergkryk/purple_ts pull request #1
Opened 2023-09-30 14:54 UTC by sergkryk

2023-10-02 14:16 UTC, Levitinn requested changes

2023-10-02 14:16 UTC, Levitinn commented on 2-typings/app.ts
> +function generateWords(number:number, words:string[] = []):string {
words: string:[] кажется эта переменная должна быть конкретного типа.
а так же стоит переписать под типы переменные TENTHS_LESS_THAN_HUNDRED, LESS_THAN_TWENTY

2023-10-06 18:04 UTC, sergkryk commented on 2-typings/app.ts
> +function generateWords(number:number, words:string[] = []):string {
> words: string:[] кажется эта переменная должна быть конкретного типа.
> а так же стоит переписать под типы переменные TENTHS_LESS_THAN_HUNDRED, LESS_THAN_TWENTY
<img width="543" alt="Screenshot 2023-10-06 at 21 02 49" src="https://github.com/sergkryk/purple_ts/assets/41703448/ecb61b0d-945c-451a-bf59-1d8bbe016236">

всё верно, это массив из строк или что вы имеете в виду под "конкретного типа"

2023-10-08 18:12 UTC, Levitinn commented on 2-typings/app.ts
> +function generateWords(number:number, words:string[] = []):string {
нет, это я напутал. все ок)

2023-10-08 18:13 UTC, Levitinn approved these changes

2023-10-08 18:54 UTC, merged