adds 4-typings
sergkryk/purple_ts pull request #2
Opened 2023-10-01 17:07 UTC by sergkryk

2023-10-02 14:47 UTC, Levitinn requested changes
почему все параметры функций ты типизируешь под unknown?  у тебя ведь описаны типы, а значит, они известны. попробуй еще раз

2023-10-06 15:41 UTC, sergkryk commented
> почему все параметры функций ты типизируешь под unknown? у тебя ведь описаны типы, а значит, они известны. попробуй еще раз

function isObject - unknown так как проверяю действительно ли это объект, type-guard
function isSuccess(response: unknown) - я не знаю что получу в ответе, далее проверяю что это действительно то, что мне нужно с помощью type-guard и сужения типов
function isUser(user: unknown) - тоже type-guard поэтому на входе может быть все что угодно
function processUser(user: unknown) - также далее есть проверка поэтому изначально unknown

В целом использовал этот тип чтобы дальше с помощью сужения типов проверять действительно ли я получил нужные данные и уже работать с ними

Сделал рефакторинг и немного упростил код.

2023-10-06 15:58 UTC, Levitinn commented
> > почему все параметры функций ты типизируешь под unknown? у тебя ведь описаны типы, а значит, они известны. попробуй еще раз
> 
> function isObject - unknown так как проверяю действительно ли это объект, type-guard function isSuccess(response: unknown) - я не знаю что получу в ответе, далее проверяю что это действительно то, что мне нужно с помощью type-guard и сужения типов function isUser(user: unknown) - тоже type-guard поэтому на входе может быть все что угодно function processUser(user: unknown) - также далее есть проверка поэтому изначально unknown
> 
> В целом использовал этот тип чтобы дальше с помощью сужения типов проверять действительно ли я получил нужные данные и уже работать с ними
> 
> Сделал рефакторинг и немного упростил код.

Функции, которые делают запрос на сервер, возвращают промис, ты можешь типизировать под него, а это не unknown

2023-10-06 16:46 UTC, sergkryk commented
> > > почему все параметры функций ты типизируешь под unknown? у тебя ведь описаны типы, а значит, они известны. попробуй еще раз
> > 
> > 
> > function isObject - unknown так как проверяю действительно ли это объект, type-guard function isSuccess(response: unknown) - я не знаю что получу в ответе, далее проверяю что это действительно то, что мне нужно с помощью type-guard и сужения типов function isUser(user: unknown) - тоже type-guard поэтому на входе может быть все что угодно function processUser(user: unknown) - также далее есть проверка поэтому изначально unknown
> > В целом использовал этот тип чтобы дальше с помощью сужения типов проверять действительно ли я получил нужные данные и уже работать с ними
> > Сделал рефакторинг и немного упростил код.
> 
> Функции, которые делают запрос на сервер, возвращают промис, ты можешь типизировать под него, а это не unknown
<img width="573" alt="Screenshot 2023-10-06 at 19 44 51" src="https://github.com/sergkryk/purple_ts/assets/41703448/b510fb6d-b8d2-4dae-928f-4ce616c55abc">

метод json() возвращает any так как я не знаю что приходит с сервера, я вместо any использую unknown чтобы не уходить от типизации и возможных ошибок при обработке ответа, не понимаю что я делаю не так.

2023-10-08 18:16 UTC, Levitinn commented
> > > > почему все параметры функций ты типизируешь под unknown? у тебя ведь описаны типы, а значит, они известны. попробуй еще раз
> > > 
> > > 
> > > function isObject - unknown так как проверяю действительно ли это объект, type-guard function isSuccess(response: unknown) - я не знаю что получу в ответе, далее проверяю что это действительно то, что мне нужно с помощью type-guard и сужения типов function isUser(user: unknown) - тоже type-guard поэтому на входе может быть все что угодно function processUser(user: unknown) - также далее есть проверка поэтому изначально unknown
> > > В целом использовал этот тип чтобы дальше с помощью сужения типов проверять действительно ли я получил нужные данные и уже работать с ними
> > > Сделал рефакторинг и немного упростил код.
> > 
> > 
> > Функции, которые делают запрос на сервер, возвращают промис, ты можешь типизировать под него, а это не unknown
> 
> <img alt="Screenshot 2023-10-06 at 19 44 51" width="573" src="https://user-images.githubusercontent.com/41703448/273279904-b510fb6d-b8d2-4dae-928f-4ce616c55abc.png">
> метод json() возвращает any так как я не знаю что приходит с сервера, я вместо any использую unknown чтобы не уходить от типизации и возможных ошибок при обработке ответа, не понимаю что я делаю не так.

ты все делаешь верно, молодец. Я лишь указал тебе, что возможно сделать это иначе.

2023-10-08 18:16 UTC, Levitinn approved these changes

2023-10-08 18:52 UTC, merged